name: Blocklet Workflow

on:
  push:
    branches:
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest

    if: "! contains(toJSON(github.event.head_commit.message), '[skip ci]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Init repo
        run: make github-init

      - name: Blocklet workflow
        uses: blocklet/action-workflow@v1.1
        with:
          skip-abtnode: true
          skip-upload: false
          bundle-command: yarn release
          store-endpoint: ${{secrets.STORE_ENDPOINT_PROD}}
          store-access-token: ${{secrets.STORE_ACCESS_TOKEN_PROD}}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
